modLoader = "javafml"
loaderVersion = "[50,)"
license = "GNU AGPL 3.0"

[[mods]]
modId = "bubusteinmoneymod"
version = "${version}"
displayURL="https://modrinth.com/mod/bubustein-money"
credits="Made with passion by BUBUSTEIN"
displayName = "BUBUSTEIN's Money Mod"
authors = "BUBUSTEIN"
description='''
Ever wish Minecraft had a money mod? Search no further!

You now have Bubustein's Money Mod, which contains US Dollars, Euros, Pound sterling, Canadian dollars, and more.
Even an ATM is available where emeralds can be converted into Currency to be used with other players.
You can resume using the village's trading hall because it works in reverse.
'''
logoFile = "icon.png"

[[dependencies.bubusteinmoneymod]]
modId = "forge"
mandatory = true
versionRange = "[50,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bubusteinmoneymod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.6,1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bubusteinmoneymod]]
modId = "architectury"
mandatory = true
versionRange = "[12.1.2,)"
ordering = "AFTER"
side = "BOTH"
