modLoader = "javafml"
loaderVersion = "[36,)"
license = "GNU AGPL 3.0"

[[mods]]
modId = "bubusteinmoneymod"
version = "${version}"
displayURL="https://modrinth.com/mod/bubustein-money"
credits="Made with passion by BUBUSTEIN"
displayName = "BUBUSTEIN's Money Mod"
authors = "BUBUSTEIN"
description='''
Ever wish Minecraft had a money mod? Search no further!

You now have Bubustein's Money Mod, which contains US Dollars, Euros, Pound sterling, Canadian dollars, and more.
Even an ATM is available.
'''
logoFile = "icon.png"
[modproperties.bubusteinmoneymod]
catalogueImageIcon="icon.png"
[[dependencies.bubusteinmoneymod]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.bubusteinmoneymod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.bubusteinmoneymod]]
modId = "architectury"
mandatory = true
versionRange = "[1.32.68,)"
ordering = "NONE"
side = "BOTH"