modLoader = "javafml"
loaderVersion = "[2,)"
license = "GNU AGPL 3.0"

[[mods]]
modId = "bubusteinmoneymod"
version = "${version}"
displayURL="https://modrinth.com/mod/bubustein-money"
credits="Made with passion by BUBUSTEIN"
displayName = "BUBUSTEIN's Money Mod"
authors = "BUBUSTEIN"
description='''
Ever wish Minecraft had a money mod? Search no further!

You now have Bubustein's Money Mod, which contains US Dollars, Euros, Pound sterling, Canadian dollars, and more.
Even an ATM is available.
'''
logoFile = "icon.png"
[[mixins]]
config = "bubusteinmoneymod-common.mixins.json"
[[mixins]]
config = "bubusteinmoneymod.mixins.json"

[[dependencies.bubusteinmoneymod]]
modId = "neoforge"
type= "required"
versionRange = "[21.0.143,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bubusteinmoneymod]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bubusteinmoneymod]]
modId = "architectury"
type = "required"
versionRange = "[13.0.3,)"
ordering = "NONE"
side = "BOTH"