name: Sync Readme Files

on:
  push:
    branches:
      - 21.x  # Ramura principală
    paths:
      - 'README.md'
      - 'README_CURSEFORGE.md'
  workflow_dispatch:  # Permite rularea manuală

jobs:
  sync-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history to ensure branches are available

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Get all branches
        id: get-branches
        run: |
          # Fetch all remote branches
          git fetch --all

          # Get a list of all branches except the main branch
          branches=$(git branch -r | grep -v '21.x' | sed 's/origin\///' | grep -v 'HEAD' | awk '{print $1}')

          # Check if we have branches
          if [ -z "$branches" ]; then
            echo "No branches to sync"
            exit 0
          fi

          echo "BRANCHES=$branches" >> $GITHUB_ENV

      - name: Sync README files
        run: |
          # Loop through all branches and sync files
          for branch in $BRANCHES; do
            echo "Syncing to branch: $branch"
            git checkout $branch
            git checkout 21.x -- README.md README_CURSEFORGE.md
            git add README.md README_CURSEFORGE.md
            git commit -m "Sync README files from 21.x" || echo "No changes to commit"
            git push origin $branch
          done
        env:
          GIT_AUTHOR_NAME: "GitHub Actions"
          GIT_AUTHOR_EMAIL: "actions@github.com"
          GIT_COMMITTER_NAME: "GitHub Actions"
          GIT_COMMITTER_EMAIL: "actions@github.com"

