name: Sync Readme Files

on:
  push:
    branches:
      - 21.x
    paths:
      - 'README.md'
      - 'README_CURSEFORGE.md'
  workflow_dispatch:

jobs:
  sync-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GIT_TOKEN }}

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Get all branches
        id: get-branches
        run: |
          git fetch --all
          branches=$(git branch -r | grep -v 'origin/21.x' | sed 's/origin\///' | grep -v 'HEAD' | awk '{print $1}')
          if [ -z "$branches" ]; then
            echo "No branches to sync"
            exit 0
          fi
          echo "$branches" > branches.txt

      - name: Sync README files
        run: |
          while IFS= read -r branch; do
            echo "Syncing to branch: $branch"
            git checkout $branch
            git checkout 21.x -- README.md README_CURSEFORGE.md
            git add README.md README_CURSEFORGE.md
            git commit -m "Sync README files from 21.x" || echo "No changes to commit"
            git push origin $branch
          done < branches.txt
        env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
