name: Sync Readme Files

on:
  push:
    branches:
      - 21.x  # Ramura principală
    paths:
      - 'README.md'
      - 'README_CURSEFORGE.md'
  workflow_dispatch:  # Permite rularea manuală

jobs:
  sync-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history to ensure branches are available

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Get all branches
        id: get-branches
        run: |
          branches=$(git branch -r | grep -v '\->' | grep -v '21.x' | sed 's/origin\///')
          echo "BRANCHES=$branches" >> $GITHUB_ENV

      - name: Sync README files
        run: |
          for branch in $BRANCHES; do
            git checkout $branch
            git checkout 21.x -- README.md README_CURSEFORGE.md
            git add README.md README_CURSEFORGE.md
            git commit -m "Sync README files from 21.x"
            git push origin $branch
          done
        env:
          GIT_AUTHOR_NAME: "GitHub Actions"
          GIT_AUTHOR_EMAIL: "actions@github.com"
          GIT_COMMITTER_NAME: "GitHub Actions"
          GIT_COMMITTER_EMAIL: "actions@github.com"

